server:
  port: 8888
---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cravatsc/demo-config
          searchPaths: config
          default-label: dev
---
spring:
  profiles: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cravatsc/demo-config
          searchPaths: config
          default-label: prod
---
spring:
  profiles: test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/cravatsc/demo-config
          searchPaths: config
          default-label: main